steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "us-central1-docker.pkg.dev/$PROJECT_ID/sdlc-demo/recommendation-app:latest", "recommendation-app"]
images: ["us-central1-docker.pkg.dev/$PROJECT_ID/sdlc-demo/recommendation-app:latest"]
options:
  requestedVerifyOption: VERIFIED
